insert into department (id, name) values (1, 'Department 1');
insert into department (id, name) values (2, 'Department 2');
insert into department (id, name) values (3, 'Department 3');
insert into department (id, name) values (4, 'Department 4');
insert into department (id, name) values (5, 'Department 5');
insert into department (id, name) values (6, 'Department 6');
insert into department (id, name) values (7, 'Department 7');
insert into department (id, name) values (8, 'Department 8');
insert into department (id, name) values (9, 'Department 9');
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id) values (1, 'John', 'Smith', 'Surgeon', 10000, 41, '1980-02-02' ,1);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id) values (2, 'Adam', 'Hamilton', 'Surgeon', 12000, 38,'1983-03-03', 1);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id) values (3, 'Tracy', 'Smith', 'Cardiologist', 15000, 36, '1985-02-02',1);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id) values (4, 'Lucy', 'Kim', 'Surgeon', 13000, 31, '1990-02-01' , 2);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id) values (5, 'Peter', 'Wright', 'Neurologist', 50000, 31, '1990-06-02',4);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id) values (6, 'Alan', 'Murray', 'Surgeon', 20000, 31, '1990-07-02',4);
insert into employee (id, first_name, last_name, position, salary, age, birthday, department_id) values (7, 'Pamela', 'Anderson', 'Endocrinologist', 7000, 31, '1990-08-02',4);